from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(457, 290)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ID_input = QtWidgets.QLineEdit(Form)
        self.ID_input.setObjectName("ID_input")
        self.horizontalLayout.addWidget(self.ID_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sort_type = QtWidgets.QLineEdit(Form)
        self.sort_type.setObjectName("sort_type")
        self.horizontalLayout_2.addWidget(self.sort_type)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.roast_text = QtWidgets.QLineEdit(Form)
        self.roast_text.setObjectName("roast_text")
        self.horizontalLayout_3.addWidget(self.roast_text)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.consistency_text = QtWidgets.QLineEdit(Form)
        self.consistency_text.setObjectName("consistency_text")
        self.horizontalLayout_4.addWidget(self.consistency_text)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.description_text = QtWidgets.QLineEdit(Form)
        self.description_text.setObjectName("description_text")
        self.horizontalLayout_7.addWidget(self.description_text)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.price_text = QtWidgets.QLineEdit(Form)
        self.price_text.setObjectName("price_text")
        self.horizontalLayout_6.addWidget(self.price_text)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.volume_text = QtWidgets.QLineEdit(Form)
        self.volume_text.setObjectName("volume_text")
        self.horizontalLayout_5.addWidget(self.volume_text)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.update_button = QtWidgets.QPushButton(Form)
        self.update_button.setObjectName("update_button")
        self.horizontalLayout_9.addWidget(self.update_button)
        self.add_entry_button = QtWidgets.QPushButton(Form)
        self.add_entry_button.setObjectName("add_entry_button")
        self.horizontalLayout_9.addWidget(self.add_entry_button)
        self.verticalLayout.addLayout(self.horizontalLayout_9)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID:"))
        self.label_2.setText(_translate("Form", "Sort Name:"))
        self.label_3.setText(_translate("Form", "Degree of roast:"))
        self.label_4.setText(_translate("Form", "Ground/In grains:"))
        self.label_7.setText(_translate("Form", "Description:"))
        self.label_5.setText(_translate("Form", "Price:"))
        self.label_6.setText(_translate("Form", "Volume package:"))
        self.update_button.setText(_translate("Form", "Update"))
        self.add_entry_button.setText(_translate("Form", "Add"))
